name: banking

services:
  web:
    build: ./webapp
    image: satkavsahked/banking-webapp:latest
    environment:
      - PORT=8000
    deploy:
      replicas: 4
    volumes:
      - app-data:/usr
    stop_signal: SIGINT
    networks:
      - backend
      - loadbalancing
    depends_on:
      db:
        condition: service_healthy
  db:
    build: ./mysql
    image: satkavsahked/banking-mysql:latest
    container_name: mysql-container
    environment:
      - PORT=3306
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-proot", "-e", "use bank;"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - backend
  nginx:
    build: ./nginx
    image: satkavashked/banking-nginx:latest
    container_name: banking-nginx
    ports:
      - "80:80"
    networks:
      - loadbalancing
    depends_on:
      - web

volumes:
    app-data:
    db-data:

networks:
  backend:
  loadbalancing:
