upstream web {
    server web:8000;
}

server {
    listen 80;

    include /etc/nginx/mime.types;

    location / {
        proxy_pass http://web/;
        proxy_pass_header Authorization;
        proxy_set_header Authorization $http_authorization;
    }
}